spring.application.name=psyconnect_backend

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/psyconnect_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:051200}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Servidor
server.port=${PORT:8080}

# Correo Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=psyconnecta@gmail.com
spring.mail.password=${MAIL_PASSWORD:pmxt bysm hwfc xipa}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true